### ISSUE TITLE
New icon needed

### ISSUE THREAD

**Issue by bleakgrey** [bleakgrey/tootle#1]
This application needs an icon. If you're willing to help, please contact me.

**Comment by CallMeFib3r** [comment]
Hi @bleakgrey,
I would like to contribute to your project by creating an icon. If you have some tips or things you want me to include please let me know!

**Comment by bleakgrey** [comment]
Hey @CallMeFib3r, thanks for your willingness to contribute!

Here's a list of useful links that may help you:
- Icon [templates](https://github.com/micahilbery/elementary-icon-templates) for elementary OS (please use the square one)
- elementary OS iconography [guidelines](https://elementary.io/docs/human-interface-guidelines#iconography). Nothing too extraordinary, just general sensible tips
- Mastodon has a [press kit](https://joinmastodon.org/press-kit.zip) with elephants and stuff. Not sure whether it can help you, but I'm going to leave this here anyway
- Mastodon's scheme colors are #282c37, #d9e1e8, #2b90d9 and #9baec8 ([link](https://joinmastodon.org/)). I use the last one as the app header color, so I guess it makes sense to primarily use this one.

I don't have any requirements besides the square icon template and that single color, please feel free to be creative. I will surely add you to the contributors list which I have to create since I don't have one :D

**Comment by CallMeFib3r** [comment]
First of al you're very welcome! Secondly thanks for all the recourses. They will come in very handy in the designing process. Before I start the process I would like to know why you choose the name Tootle. It might help me while I brainstorm. And lastly since your project is a client for an existing project, do you want me to make the logos somewhat relatable? Should I work with an elephant jus like Mastodon or do you want me to create something fresh?

**Comment by bleakgrey** [comment]
Would you mind if we switched to email? Please ping me at bleakgrey@gmail.com

**Comment by CallMeFib3r** [comment]
All the files can be found over here. https://drive.google.com/open?id=17t1xOCPIG7R2QGqijeL-rrlk5sUAIEPD

**Comment by bleakgrey** [comment]
Just merged in the master branch. Thank you! :tada:
