### ISSUE TITLE
Update on project status

### ISSUE THREAD

**Issue by okias** [bleakgrey/tootle#171]
Hello guys,

it seems (as looking at developer activity on github) that Tootle project is not developed nor maintained anymore. Anyone interested to at least maintain it (until dev step up) or overtake development?

This application would be really interesting for Linux mobile phones and also it has potential to get integrated as official GNOME application.

**Comment by davidak** [comment]
The developer works on a refactored version. (see activity here https://github.com/bleakgrey/tootle/commits/refactor)

If you care about the project, consider donating to the developer: https://liberapay.com/bleakgrey/donate

There is also an active fork that fixed some problems: https://github.com/cleac/tootle

**Comment by okias** [comment]
oh, that's great, thanks for information. Not sure why this branch hasn't showed in developer activity in github overview :)

**Comment by FedericoCeratto** [comment]
@okias Tootle is already in Debian: https://packages.debian.org/sid/tootle but I'll consider removing it in absence of new releases due to the many bugs.

**Comment by bleakgrey** [comment]
@okias Please split the list into separate issues if they still stand.

**Comment by davidak** [comment]
@bleakgrey Welcome back!

Do you plan a release soon?

Please consider collaborating with the community, like @cleac who maintains a fork to make the project usable again. https://github.com/cleac/olifant/issues/30 With the goal to make the best version of this.

**Comment by bleakgrey** [comment]
@davidak There are many WIP things and even more things that I haven't even started (re)writing. Refactoring a project like this turned out to have... intricacies (because Mastodon is developing _really fast_ and I've made bad architectural decisions at the start of the development), but I'm trying my best to make the release happen ASAP :)

@cleac's Olifant does have several ideas that I like (he even proposed several pull requests), so I think they will be incorporated to "upstream" Tootle. I get excited about just thinking that Tootle has a fork now!

However, I don't think that I will be contributing new features to Olifant because I'm moving from eOS as a target distro. I've rewritten core widgets to use Glade and utilize more GNOME-centered look and feel. @cleac will have to either retrofit new features somehow or drop them altogether.

**Comment by bleakgrey** [comment]
I felt bad about dropping eOS, but since Olifant got released I'm actually relieved that someone decided to maintain the old eOS codebase. I can finally resume working on things that _I want_ rather than things that _I have_ to support.

I realize that this may be taxing on @cleac, so I'm happy to help him should he need any support.
