### ISSUE TITLE
Don't show the account switcher/toot buttons in the headerbar on sub-views

### ISSUE THREAD

**Issue by bertob** [bleakgrey/tootle#197]
When on a sub-view (e.g. someone's profile, or a toot thread), the headerbar should not contain global actions such as the account menu. It's conceptually weird since the buttons exist on multiple levels of hierarchy, doesn't make sense with things like the HdyDeck "back" gesture, and causes the back button to not be the leftmost button, which feels a bit off.

![image](https://user-images.githubusercontent.com/1908896/87229506-beb9ef80-c3a8-11ea-83f3-ad18a7249a76.png)

**Comment by ranfdev** [comment]
The toot btn is necessary everywhere, because sometimes you want to toot
about the thing you are reading.
The account btn is necessary everywhere, so you can interact (favourite,
boost, reply) using another account.

I agree the position of the back btn is akward, but we should also find a
way to accomplish the previous things without much trouble.

**Comment by ranfdev** [comment]
Maybe we could put the account switcher to the right, and put the toot btn
inside a fab.

https://material.io/components/buttons-floating-action-button

This application has done something similar, putting the add btn inside a
fab
https://flathub.org/apps/details/com.github.alainm23.planner

**Comment by bertob** [comment]
> The toot btn is necessary everywhere, because sometimes you want to toot
about the thing you are reading.
> The account btn is necessary everywhere, so you can interact (favourite,
boost, reply) using another account.

Dunno, mobile apps (e.g. Tusky) seem to do just fine without either of these...

**Comment by bleakgrey** [comment]
As @ranfdev stated, it makes no sense to go back all the way back to the timelines just to post a status. Speaking from personal experience, there are times I want to post something unrelated to the current thread view.

Not sure about the fab. Not only it is alien to the GNOME HIGs, it is also to be the third widget (after the headerbar and the bottom timeline switcher) that obscures the content view on mobiles.

As far as the Account button is concerned, I don't think it is fair to remove it because it contains shortcuts to Favorites, Bookmarks, DMs, and some global actions like Search and Settings. Again, closing all secondary views just to tweak the text size feels like a burden. The current layout is the compromise I stick to because Tootle can't have multiple columns ("Advanced interface mode" in Mastodon's terminology). Also, dynamic account switching (#189) feature is planned and depends on the Account button being visible from anywhere.

We could rearrange the header layout, but hiding the Compose and Account buttons completely objectively imposes artificial inconveniences for the user (especially when there is some space left in the header bar) and degrades planned functionality.

**Comment by bleakgrey** [comment]
Corebird uses (well, *used* since Twitter has shutdown most of its APIs) a similar header bar layout.

![image](https://user-images.githubusercontent.com/20158357/87230958-d8186700-c3bb-11ea-999d-d71e0773818b.png)

**Comment by ranfdev** [comment]
What about putting the back btn all the way to the left, inside a revealer, so when it get's shown, it pushes the other buttons to the right with a nice animation

**Comment by bleakgrey** [comment]
Can do. @bertob, what do you think?

**Comment by bertob** [comment]
Corebird's design should definitely not be used as an example for anything :)

I'd be interested in looking at some relevant art. What do other (well-designed) desktop/large screen clients do here?

**Comment by bleakgrey** [comment]
Well... there are not so many of them :)

**Comment by bleakgrey** [comment]
Corebird is the only neat client I'm aware of (even though it's not for Mastodon).

The ones for Mastodon are either really WIP (@ranfdev's Elefanto, https://gitlab.gnome.org/World/Social, many others), really into KDE (Choqok), Electron- (Whalebird) or CLI-only (madonctl).

**Comment by bertob** [comment]
I was thinking more of Twitter clients, e.g. for macOS or iPad.

![image](https://user-images.githubusercontent.com/1908896/87235187-d5c50580-c3d9-11ea-8ea9-d2605f09df84.png)

![image](https://user-images.githubusercontent.com/1908896/87235265-98ad4300-c3da-11ea-9afd-ebfcf9242617.png)

Looks like most of them have a sidebar for navigation, which unfortunately is not ideal for making it adaptive. I guess it could be doable with a transient sidebar, or by moving some sidebar elements into a switcher on mobile, but it'd require a pretty significant rethinking of the UI.

All of that said, I'm not convinced this is critical enough to warrant designing the entire app around. I'd guess the most people use Mastodon (and Twtitter, and similar things) primarily on phones, where these things are not globally accessible, and it doesn't seem to be a problem :)
