### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by bleakgrey** [bleakgrey/tootle#9]
After a couple of timeline updates Tootle RAM usage gets abnormally high. Not sure what leaks exactly though.

**Comment by alcinnz** [comment]
After a first look the code looks pretty good, and I understand your frustration. And I don't think the issue is with libsoup or libjson-glib as I've used both with no problems (beyond the screens full informing me that "deprecated is deprecated").

Maybe the issue is with displaying all those statuses? I can see each one individually taking up a decent chunk of memory, and you are displaying a lot of them.

I can think of two fixes if that's the problem. Either you switch to using a Gtk.TreeView (which is more memory efficient due to it's use of the flyweight pattern), or you find a way to only keep the statuses currently onscreen in memory (Apple did something similar for early iPhones). That said either of these solutions will require significant reworking of your code. But for the former [elementary Mail](https://github.com/elementary/mail) will work as good sample code.

**Comment by bleakgrey** [comment]
It's weird, actually. PixBufs should release themselves immediately after their holder widgets are destroyed (which I do explicitly)

**Comment by martensitingale** [comment]
I've been looking for the leak here a bit more, instrumenting constructors/destructors and using https://github.com/danni/gobject-list

It seems widgets are not getting leaked but SoupMessages may be. I'll run a more controlled experiment to see if I can pin it down with more certainty.

**Comment by martensitingale** [comment]
To rule out a confounding factor, I need to double-check the generated C and see which types are created with `g_object_new` and which go through other possible routes (structs with their own constructors/refcounting, and/or maybe other GObject construction functions that avoid LD_PRELOAD interception on `g_object_new`).

**Comment by bleakgrey** [comment]
Yeah, I had such an idea. You may want to remove `msg.free ()` in https://github.com/bleakgrey/tootle/blob/master/src/Network.vala#L75 then.

Maybe it's connected to image attachments and the downloaded image data doesn't get freed automatically?

**Comment by martensitingale** [comment]
I did a bunch of profiling with the tool I mentioned above. Here's the breakdown.

We *are* leaking `SoupMessage`s, because the ImageCache's "finished" signal callbacks add references to them. I'll push a patch for that right now that simply disconnects the callbacks after they run and lets things get cleaned up. But we had leaks even before the ImageCache, and we have leaks even after fixing it.

I've been using a couple scripts to process the output of the refcount debugging tool:
`diff-leaked.sh`, which when run on the text printed by a program with `LD_PRELOAD` set to `libgobject-list.so` computes lists of objects created but not finalized (this is how I found the `SoupMessage` leak):
```
#!/bin/sh
log=$1
< "$log" fgrep Created | sed -r -e 's/Created //g' | sort | cut -c 5- > created
< "$log" fgrep Finalized | sed -r -e 's/Finalized //g' | sort | cut -c 5- > finalized
diff --side-by-side created finalized | grep '[<>]' | sort -k 3
```

and `snapshot-stats.sh`, which when run on the same sort of input, but where the program got SIGUSR1 a number of times during its run, produces a file of object counts by GObject class for each checkpoint:

```
#!/bin/sh
log=$1
fgrep -B999999999 'Still Alive:' "$log" \
| grep -E -v 'Created|Finalized|destroyed|message|INFO|Still Alive:|^$' \
| csplit - -z --suppress-matched '/bjects/' '/bjects/' '{*}' -f objs

for i in objs*; do
	< "$i" awk '{print $3}' | sort | uniq -c | sort -n > $i.stats
done
```

Before and after refreshing the main timeline in Tootle (with the ImageCache fix) about seven times, the latter script gives heap breakdowns that differ only in the below excerpts:

Initial timeline:
```
      5 GtkButtonAccessible:
      8 GdkX11Cursor:
     13 AtkRelationSet:
     81 GtkCssImageLinear:
    139 GtkGesturePan:
    139 GtkGestureSwipe:
    149 GtkCssImageGradient:
    169 GtkGestureLongPress:
    188 GdkPixbuf:
    299 GtkGestureDrag:
    507 GtkBox:
    535 GtkIconHelper:
    657 GtkGestureMultiPress:
   1384 GtkCssNode:
   3044 GtkCssCustomGadget:
   3514 GtkStyleContext:
   3533 GtkCssWidgetNode:
   5913 GtkCssStaticStyle:
   5914 GtkCssImageBuiltin:```

After 7 or so refreshes:
```
      6 GtkButtonAccessible:
      9 GdkX11Cursor:
     14 AtkRelationSet:
    107 GtkCssImageLinear:
    190 GdkPixbuf:
    221 GtkCssImageGradient:
    319 GtkGesturePan:
    319 GtkGestureSwipe:
    349 GtkGestureLongPress:
    687 GtkBox:
    743 GtkGestureDrag:
   1255 GtkIconHelper:
   1653 GtkGestureMultiPress:
   3136 GtkCssNode:
   6668 GtkCssCustomGadget:
   8038 GtkStyleContext:
   8057 GtkCssWidgetNode:
  13638 GtkCssStaticStyle:
  13639 GtkCssImageBuiltin:```

So any heap growth we see (and we *do* see consistent heap growth on every refresh) should be accounted for in the difference between these two breakdowns. And, in fact, I *don't* see similar apparent leaks of `GtkCssWidgetNode`s, `GtkCssStaticStyle`s, or `GtkCssImageBuiltin`s in other GTK programs such as one that simply creates/shows/destroys a `GtkButton` over and over. But Tootle doesn't touch any of the CSS stuff directly; it's only used in widget implementations during rendering. So I'm pretty confused and will have to dig deeper... but this is what I have so far.

**Comment by martensitingale** [comment]
The next experiment to run is seeing if `GtkBox` population correlates with number of timeline refreshes.

**Comment by bleakgrey** [comment]
Well that's... perplexing. The situation with Soup messages is understandable, but honestly I expected basically _everything else except CSS stuff_ to be the possible reason of the leak. It occurs to me that I haven't checked whether Granite's avatar widget has something to do with this.

Thank you for your efforts! I'll check if I use anything else that might cause problems with CSS.

**Comment by martensitingale** [comment]
It looks like we're leaking `GtkBox`es and *those* simply own CSS stuff.

**Comment by bleakgrey** [comment]
I recall 2 major sources of them: `StatusWidget`s and views that inherit `AbstractView`. I don't think that the latter is ever mutable or even destroyable though (unless lots of them were opened in the main nav stack).

**Comment by martensitingale** [comment]
By changing all the Gtk.Box constructors to pass unique spacing values and patching the gobject list tool to printing spacing of Gtk.Box instances when it gets USR1 (ugly but works), I identified the Box in question: `Tootle.AttachmentBox.box`.

But these are on every status, so why do we leak exactly 30 per refresh?

So I looked at what other things there are 30 of. We request 30 notifications:

`var url2 = "%s/api/v1/notifications?limit=30".printf (Tootle.accounts.formal.instance);`

And indeed, if I remove the notifications query from `request` on `NotificationsView`, I see no significant memory usage increase when doing a refresh.

We're getting closer!
