### ISSUE TITLE
Start in Tray / Minimize to Tray

### ISSUE THREAD

**Issue by mase76** [bleakgrey/tootle#91]
Hi!
It would be nice, if the application could be started minimized in tray and could be minimized to tray.

**Comment by HelmicNewciv** [comment]
Gonna second this.  I'd love to be able to click on a notification, pop up and respond to a toot, and then X out of the window and go back to what I was doing and still be ready to respond to new stuff without having Tootle sitting there on my taskbar at all times.

**Comment by bleakgrey** [comment]
Kind of implemented using "Always receive notifications".

**Comment by HelmicNewciv** [comment]
It's not, really.  Always receive notifications doesn't let you minimize it to the tray like other social media applications, like IRC chat clients, Discord, et cetera.  It doesn't seem like that setting will send notifications of toots even when the application isn't in the taskbar.

It's a shame, because the only way to accomplish this with any Mastodon client seems to be to literally just put the website in an Electron wrapper and have _that_ sit in the tray and send notifications.  It's literally what I do right now for lack of an alternative.

**Comment by bleakgrey** [comment]
Several users have indicated their interest in a tray icon support, but I have to stick to the current behavior because Tootle is designed for elementary OS and its guidelines (for now). 

Even though the tray icon is not implemented, turning on that setting will make Tootle run in background. It means that the notification service will always dispatch notifications even if the app window is closed.

Please file a bug report if Tootle doesn't show notifications even if that setting is turned on.
